# Generated by Django 5.1.14 on 2025-11-14 06:33

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0246_endpoint_idx_ep_product_lower_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Repository name in 'org/repo' format", max_length=255, verbose_name='Repository Name')),
                ('github_repo_id', models.BigIntegerField(help_text="GitHub's internal numeric repository ID", unique=True, verbose_name='GitHub Repository ID')),
                ('github_url', models.URLField(help_text='Full GitHub repository URL', max_length=600, verbose_name='GitHub URL')),
                ('last_commit_date', models.DateTimeField(blank=True, help_text='Date of the last commit to the repository', null=True, verbose_name='Last Commit Date')),
                ('active_contributors_90d', models.IntegerField(default=0, help_text='Number of active contributors in the last 90 days', verbose_name='Active Contributors (90d)')),
                ('days_since_last_commit', models.IntegerField(blank=True, help_text='Calculated: days elapsed since last commit', null=True, verbose_name='Days Since Last Commit')),
                ('readme_summary', models.TextField(blank=True, help_text='Auto-generated summary of repository README', max_length=500, verbose_name='README Summary')),
                ('readme_length', models.IntegerField(default=0, help_text='Character count of README file', verbose_name='README Length')),
                ('primary_language', models.CharField(blank=True, help_text='Primary programming language detected', max_length=50, verbose_name='Primary Language')),
                ('primary_framework', models.CharField(blank=True, help_text='Primary framework detected from README', max_length=50, verbose_name='Primary Framework')),
                ('codeowners_content', models.TextField(blank=True, help_text='Raw content of CODEOWNERS file', verbose_name='CODEOWNERS Content')),
                ('ownership_confidence', models.IntegerField(default=0, help_text='Confidence score (0-100) for ownership data quality', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ownership Confidence')),
                ('has_dockerfile', models.BooleanField(default=False, help_text='Repository contains Dockerfile', verbose_name='Has Dockerfile')),
                ('has_kubernetes_config', models.BooleanField(default=False, help_text='Repository contains K8s manifests or Helm charts', verbose_name='Has Kubernetes Config')),
                ('has_ci_cd', models.BooleanField(default=False, help_text='Repository has CI/CD configuration', verbose_name='Has CI/CD')),
                ('has_terraform', models.BooleanField(default=False, help_text='Repository contains Terraform IaC', verbose_name='Has Terraform')),
                ('has_deployment_scripts', models.BooleanField(default=False, help_text='Repository contains deployment scripts', verbose_name='Has Deployment Scripts')),
                ('has_procfile', models.BooleanField(default=False, help_text='Repository contains Procfile for PaaS deployment', verbose_name='Has Procfile')),
                ('has_environments', models.BooleanField(default=False, help_text='GitHub environments configured', verbose_name='Has Environments')),
                ('has_releases', models.BooleanField(default=False, help_text='GitHub releases exist', verbose_name='Has Releases')),
                ('has_branch_protection', models.BooleanField(default=False, help_text='Protected main branch configured', verbose_name='Has Branch Protection')),
                ('has_monitoring_config', models.BooleanField(default=False, help_text='Monitoring configuration present', verbose_name='Has Monitoring Config')),
                ('has_ssl_config', models.BooleanField(default=False, help_text='SSL/TLS configuration present', verbose_name='Has SSL Config')),
                ('has_database_migrations', models.BooleanField(default=False, help_text='Database migration files present', verbose_name='Has Database Migrations')),
                ('recent_commits_30d', models.BooleanField(default=False, help_text='Has commits in last 30 days', verbose_name='Recent Commits (30d)')),
                ('active_prs_30d', models.BooleanField(default=False, help_text='Has PRs in last 30 days', verbose_name='Active PRs (30d)')),
                ('multiple_contributors', models.BooleanField(default=False, help_text='More than 1 contributor in 90 days', verbose_name='Multiple Contributors')),
                ('has_dependabot_activity', models.BooleanField(default=False, help_text='Dependabot updates detected', verbose_name='Has Dependabot Activity')),
                ('recent_releases_90d', models.BooleanField(default=False, help_text='Has releases in last 90 days', verbose_name='Recent Releases (90d)')),
                ('consistent_commit_pattern', models.BooleanField(default=False, help_text='Regular commit schedule detected', verbose_name='Consistent Commit Pattern')),
                ('has_tests', models.BooleanField(default=False, help_text='Test directories present', verbose_name='Has Tests')),
                ('has_documentation', models.BooleanField(default=False, help_text='Documentation directory or detailed README', verbose_name='Has Documentation')),
                ('has_api_specs', models.BooleanField(default=False, help_text='OpenAPI/Swagger specs present', verbose_name='Has API Specs')),
                ('has_codeowners', models.BooleanField(default=False, help_text='CODEOWNERS file present', verbose_name='Has CODEOWNERS')),
                ('has_security_md', models.BooleanField(default=False, help_text='Security policy documented', verbose_name='Has SECURITY.md')),
                ('is_monorepo', models.BooleanField(default=False, help_text='Multiple projects in single repository', verbose_name='Is Monorepo')),
                ('has_security_scanning', models.BooleanField(default=False, help_text='Security scanning in CI/CD', verbose_name='Has Security Scanning')),
                ('has_secret_scanning', models.BooleanField(default=False, help_text='Secret scanning enabled', verbose_name='Has Secret Scanning')),
                ('has_dependency_scanning', models.BooleanField(default=False, help_text='Dependency scanning configured', verbose_name='Has Dependency Scanning')),
                ('has_gitleaks_config', models.BooleanField(default=False, help_text='Gitleaks secret detection configured', verbose_name='Has Gitleaks Config')),
                ('has_sast_config', models.BooleanField(default=False, help_text='SAST tools configured', verbose_name='Has SAST Config')),
                ('last_alert_sync', models.DateTimeField(blank=True, help_text='Timestamp of last GitHub alerts synchronization', null=True, verbose_name='Last Alert Sync')),
                ('dependabot_alert_count', models.IntegerField(default=0, help_text='Number of open Dependabot alerts', verbose_name='Dependabot Alert Count')),
                ('codeql_alert_count', models.IntegerField(default=0, help_text='Number of open CodeQL alerts', verbose_name='CodeQL Alert Count')),
                ('secret_scanning_alert_count', models.IntegerField(default=0, help_text='Number of open secret scanning alerts', verbose_name='Secret Scanning Alert Count')),
                ('cached_finding_counts', models.JSONField(blank=True, default=dict, help_text='Pre-computed finding counts by severity: {critical: N, high: N, ...}', verbose_name='Cached Finding Counts')),
                ('tier', models.CharField(choices=[('tier1', 'Tier 1 - Critical'), ('tier2', 'Tier 2 - High'), ('tier3', 'Tier 3 - Medium'), ('tier4', 'Tier 4 - Low'), ('archived', 'Archived')], default='tier4', help_text='Computed criticality tier based on signals and activity', max_length=10, verbose_name='Repository Tier')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'ordering': ['name'],
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='product',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='product',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='product',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='finding',
            name='auto_triage_decision',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Triage'), ('DISMISS', 'Auto-Dismissed'), ('ESCALATE', 'Auto-Escalated'), ('ACCEPT_RISK', 'Auto-Accepted Risk')], default='PENDING', help_text='Automated triage decision based on rules', max_length=20, verbose_name='Auto-Triage Decision'),
        ),
        migrations.AddField(
            model_name='finding',
            name='auto_triage_reason',
            field=models.TextField(blank=True, help_text='Explanation for the auto-triage decision', verbose_name='Auto-Triage Reason'),
        ),
        migrations.AddField(
            model_name='finding',
            name='auto_triaged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when auto-triage was performed', null=True, verbose_name='Auto-Triaged At'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='auto_triage_decision',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Triage'), ('DISMISS', 'Auto-Dismissed'), ('ESCALATE', 'Auto-Escalated'), ('ACCEPT_RISK', 'Auto-Accepted Risk')], default='PENDING', help_text='Automated triage decision based on rules', max_length=20, verbose_name='Auto-Triage Decision'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='auto_triage_reason',
            field=models.TextField(blank=True, help_text='Explanation for the auto-triage decision', verbose_name='Auto-Triage Reason'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='auto_triaged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when auto-triage was performed', null=True, verbose_name='Auto-Triaged At'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_contributors_90d',
            field=models.IntegerField(default=0, help_text='Number of active contributors in the last 90 days', verbose_name='Active Contributors (90d)'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_prs_30d',
            field=models.BooleanField(default=False, help_text='Has PRs in last 30 days', verbose_name='Active PRs (30d)'),
        ),
        migrations.AddField(
            model_name='product',
            name='codeowners_content',
            field=models.TextField(blank=True, help_text='Raw content of CODEOWNERS file', verbose_name='CODEOWNERS Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='consistent_commit_pattern',
            field=models.BooleanField(default=False, help_text='Regular commit schedule detected', verbose_name='Consistent Commit Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='days_since_last_commit',
            field=models.IntegerField(blank=True, help_text='Calculated: days elapsed since last commit', null=True, verbose_name='Days Since Last Commit'),
        ),
        migrations.AddField(
            model_name='product',
            name='github_repo_id',
            field=models.CharField(blank=True, help_text="GitHub's internal repository ID", max_length=100, verbose_name='GitHub Repository ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='github_url',
            field=models.URLField(blank=True, help_text='Full GitHub repository URL', max_length=600, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_api_specs',
            field=models.BooleanField(default=False, help_text='OpenAPI/Swagger specs present', verbose_name='Has API Specs'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_branch_protection',
            field=models.BooleanField(default=False, help_text='Protected main branch configured', verbose_name='Has Branch Protection'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_ci_cd',
            field=models.BooleanField(default=False, help_text='Repository has CI/CD configuration', verbose_name='Has CI/CD'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_codeowners',
            field=models.BooleanField(default=False, help_text='CODEOWNERS file present', verbose_name='Has CODEOWNERS'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_database_migrations',
            field=models.BooleanField(default=False, help_text='Database migration files present', verbose_name='Has Database Migrations'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_dependabot_activity',
            field=models.BooleanField(default=False, help_text='Dependabot updates detected', verbose_name='Has Dependabot Activity'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_dependency_scanning',
            field=models.BooleanField(default=False, help_text='Dependency scanning configured', verbose_name='Has Dependency Scanning'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_deployment_scripts',
            field=models.BooleanField(default=False, help_text='Repository contains deployment scripts', verbose_name='Has Deployment Scripts'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_dockerfile',
            field=models.BooleanField(default=False, help_text='Repository contains Dockerfile', verbose_name='Has Dockerfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_documentation',
            field=models.BooleanField(default=False, help_text='Documentation directory or detailed README', verbose_name='Has Documentation'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_environments',
            field=models.BooleanField(default=False, help_text='GitHub environments configured', verbose_name='Has Environments'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_gitleaks_config',
            field=models.BooleanField(default=False, help_text='Gitleaks secret detection configured', verbose_name='Has Gitleaks Config'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_kubernetes_config',
            field=models.BooleanField(default=False, help_text='Repository contains K8s manifests or Helm charts', verbose_name='Has Kubernetes Config'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_monitoring_config',
            field=models.BooleanField(default=False, help_text='Monitoring configuration present', verbose_name='Has Monitoring Config'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_procfile',
            field=models.BooleanField(default=False, help_text='Repository contains Procfile for PaaS deployment', verbose_name='Has Procfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_releases',
            field=models.BooleanField(default=False, help_text='GitHub releases exist', verbose_name='Has Releases'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_sast_config',
            field=models.BooleanField(default=False, help_text='SAST tools configured', verbose_name='Has SAST Config'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_secret_scanning',
            field=models.BooleanField(default=False, help_text='Secret scanning enabled', verbose_name='Has Secret Scanning'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_security_md',
            field=models.BooleanField(default=False, help_text='Security policy documented', verbose_name='Has SECURITY.md'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_security_scanning',
            field=models.BooleanField(default=False, help_text='Security scanning in CI/CD', verbose_name='Has Security Scanning'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_ssl_config',
            field=models.BooleanField(default=False, help_text='SSL/TLS configuration present', verbose_name='Has SSL Config'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_terraform',
            field=models.BooleanField(default=False, help_text='Repository contains Terraform IaC', verbose_name='Has Terraform'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_tests',
            field=models.BooleanField(default=False, help_text='Test directories present', verbose_name='Has Tests'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_monorepo',
            field=models.BooleanField(default=False, help_text='Multiple projects in single repository', verbose_name='Is Monorepo'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_repository_placeholder',
            field=models.BooleanField(default=False, help_text='True if this Product was created as 1:1 mapping to a GitHub repository (legacy). Will be migrated to Repository model.', verbose_name='Is Repository Placeholder'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_commit_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last commit to the repository', null=True, verbose_name='Last Commit Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='multiple_contributors',
            field=models.BooleanField(default=False, help_text='More than 1 contributor in 90 days', verbose_name='Multiple Contributors'),
        ),
        migrations.AddField(
            model_name='product',
            name='ownership_confidence',
            field=models.IntegerField(default=0, help_text='Confidence score (0-100) for ownership data quality', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ownership Confidence'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_framework',
            field=models.CharField(blank=True, help_text='Primary framework detected from README', max_length=50, verbose_name='Primary Framework'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_language',
            field=models.CharField(blank=True, help_text='Primary programming language detected', max_length=50, verbose_name='Primary Language'),
        ),
        migrations.AddField(
            model_name='product',
            name='readme_length',
            field=models.IntegerField(default=0, help_text='Character count of README file', verbose_name='README Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='readme_summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary of repository README', max_length=500, verbose_name='README Summary'),
        ),
        migrations.AddField(
            model_name='product',
            name='recent_commits_30d',
            field=models.BooleanField(default=False, help_text='Has commits in last 30 days', verbose_name='Recent Commits (30d)'),
        ),
        migrations.AddField(
            model_name='product',
            name='recent_releases_90d',
            field=models.BooleanField(default=False, help_text='Has releases in last 90 days', verbose_name='Recent Releases (90d)'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='active_contributors_90d',
            field=models.IntegerField(default=0, help_text='Number of active contributors in the last 90 days', verbose_name='Active Contributors (90d)'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='active_prs_30d',
            field=models.BooleanField(default=False, help_text='Has PRs in last 30 days', verbose_name='Active PRs (30d)'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='codeowners_content',
            field=models.TextField(blank=True, help_text='Raw content of CODEOWNERS file', verbose_name='CODEOWNERS Content'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='consistent_commit_pattern',
            field=models.BooleanField(default=False, help_text='Regular commit schedule detected', verbose_name='Consistent Commit Pattern'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='days_since_last_commit',
            field=models.IntegerField(blank=True, help_text='Calculated: days elapsed since last commit', null=True, verbose_name='Days Since Last Commit'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='github_repo_id',
            field=models.CharField(blank=True, help_text="GitHub's internal repository ID", max_length=100, verbose_name='GitHub Repository ID'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='github_url',
            field=models.URLField(blank=True, help_text='Full GitHub repository URL', max_length=600, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_api_specs',
            field=models.BooleanField(default=False, help_text='OpenAPI/Swagger specs present', verbose_name='Has API Specs'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_branch_protection',
            field=models.BooleanField(default=False, help_text='Protected main branch configured', verbose_name='Has Branch Protection'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_ci_cd',
            field=models.BooleanField(default=False, help_text='Repository has CI/CD configuration', verbose_name='Has CI/CD'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_codeowners',
            field=models.BooleanField(default=False, help_text='CODEOWNERS file present', verbose_name='Has CODEOWNERS'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_database_migrations',
            field=models.BooleanField(default=False, help_text='Database migration files present', verbose_name='Has Database Migrations'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_dependabot_activity',
            field=models.BooleanField(default=False, help_text='Dependabot updates detected', verbose_name='Has Dependabot Activity'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_dependency_scanning',
            field=models.BooleanField(default=False, help_text='Dependency scanning configured', verbose_name='Has Dependency Scanning'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_deployment_scripts',
            field=models.BooleanField(default=False, help_text='Repository contains deployment scripts', verbose_name='Has Deployment Scripts'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_dockerfile',
            field=models.BooleanField(default=False, help_text='Repository contains Dockerfile', verbose_name='Has Dockerfile'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_documentation',
            field=models.BooleanField(default=False, help_text='Documentation directory or detailed README', verbose_name='Has Documentation'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_environments',
            field=models.BooleanField(default=False, help_text='GitHub environments configured', verbose_name='Has Environments'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_gitleaks_config',
            field=models.BooleanField(default=False, help_text='Gitleaks secret detection configured', verbose_name='Has Gitleaks Config'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_kubernetes_config',
            field=models.BooleanField(default=False, help_text='Repository contains K8s manifests or Helm charts', verbose_name='Has Kubernetes Config'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_monitoring_config',
            field=models.BooleanField(default=False, help_text='Monitoring configuration present', verbose_name='Has Monitoring Config'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_procfile',
            field=models.BooleanField(default=False, help_text='Repository contains Procfile for PaaS deployment', verbose_name='Has Procfile'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_releases',
            field=models.BooleanField(default=False, help_text='GitHub releases exist', verbose_name='Has Releases'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_sast_config',
            field=models.BooleanField(default=False, help_text='SAST tools configured', verbose_name='Has SAST Config'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_secret_scanning',
            field=models.BooleanField(default=False, help_text='Secret scanning enabled', verbose_name='Has Secret Scanning'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_security_md',
            field=models.BooleanField(default=False, help_text='Security policy documented', verbose_name='Has SECURITY.md'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_security_scanning',
            field=models.BooleanField(default=False, help_text='Security scanning in CI/CD', verbose_name='Has Security Scanning'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_ssl_config',
            field=models.BooleanField(default=False, help_text='SSL/TLS configuration present', verbose_name='Has SSL Config'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_terraform',
            field=models.BooleanField(default=False, help_text='Repository contains Terraform IaC', verbose_name='Has Terraform'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='has_tests',
            field=models.BooleanField(default=False, help_text='Test directories present', verbose_name='Has Tests'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='is_monorepo',
            field=models.BooleanField(default=False, help_text='Multiple projects in single repository', verbose_name='Is Monorepo'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='is_repository_placeholder',
            field=models.BooleanField(default=False, help_text='True if this Product was created as 1:1 mapping to a GitHub repository (legacy). Will be migrated to Repository model.', verbose_name='Is Repository Placeholder'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='last_commit_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last commit to the repository', null=True, verbose_name='Last Commit Date'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='multiple_contributors',
            field=models.BooleanField(default=False, help_text='More than 1 contributor in 90 days', verbose_name='Multiple Contributors'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='ownership_confidence',
            field=models.IntegerField(default=0, help_text='Confidence score (0-100) for ownership data quality', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ownership Confidence'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='primary_framework',
            field=models.CharField(blank=True, help_text='Primary framework detected from README', max_length=50, verbose_name='Primary Framework'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='primary_language',
            field=models.CharField(blank=True, help_text='Primary programming language detected', max_length=50, verbose_name='Primary Language'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='readme_length',
            field=models.IntegerField(default=0, help_text='Character count of README file', verbose_name='README Length'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='readme_summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary of repository README', max_length=500, verbose_name='README Summary'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='recent_commits_30d',
            field=models.BooleanField(default=False, help_text='Has commits in last 30 days', verbose_name='Recent Commits (30d)'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='recent_releases_90d',
            field=models.BooleanField(default=False, help_text='Has releases in last 90 days', verbose_name='Recent Releases (90d)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_decision", "auto_triage_reason", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."auto_triage_decision", NEW."auto_triage_reason", NEW."auto_triaged_at", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='a1ad659f893dbad835bc24e9745a03e31a1b8f59', operation='INSERT', pgid='pgtrigger_insert_insert_2fbbb', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."auto_triage_decision" IS DISTINCT FROM (NEW."auto_triage_decision") OR OLD."auto_triage_reason" IS DISTINCT FROM (NEW."auto_triage_reason") OR OLD."auto_triaged_at" IS DISTINCT FROM (NEW."auto_triaged_at") OR OLD."component_name" IS DISTINCT FROM (NEW."component_name") OR OLD."component_version" IS DISTINCT FROM (NEW."component_version") OR OLD."cve" IS DISTINCT FROM (NEW."cve") OR OLD."cvssv3" IS DISTINCT FROM (NEW."cvssv3") OR OLD."cvssv3_score" IS DISTINCT FROM (NEW."cvssv3_score") OR OLD."cvssv4" IS DISTINCT FROM (NEW."cvssv4") OR OLD."cvssv4_score" IS DISTINCT FROM (NEW."cvssv4_score") OR OLD."cwe" IS DISTINCT FROM (NEW."cwe") OR OLD."date" IS DISTINCT FROM (NEW."date") OR OLD."defect_review_requested_by_id" IS DISTINCT FROM (NEW."defect_review_requested_by_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duplicate" IS DISTINCT FROM (NEW."duplicate") OR OLD."duplicate_finding_id" IS DISTINCT FROM (NEW."duplicate_finding_id") OR OLD."dynamic_finding" IS DISTINCT FROM (NEW."dynamic_finding") OR OLD."effort_for_fixing" IS DISTINCT FROM (NEW."effort_for_fixing") OR OLD."epss_percentile" IS DISTINCT FROM (NEW."epss_percentile") OR OLD."epss_score" IS DISTINCT FROM (NEW."epss_score") OR OLD."false_p" IS DISTINCT FROM (NEW."false_p") OR OLD."file_path" IS DISTINCT FROM (NEW."file_path") OR OLD."fix_available" IS DISTINCT FROM (NEW."fix_available") OR OLD."hash_code" IS DISTINCT FROM (NEW."hash_code") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."is_mitigated" IS DISTINCT FROM (NEW."is_mitigated") OR OLD."kev_date" IS DISTINCT FROM (NEW."kev_date") OR OLD."known_exploited" IS DISTINCT FROM (NEW."known_exploited") OR OLD."last_reviewed" IS DISTINCT FROM (NEW."last_reviewed") OR OLD."last_reviewed_by_id" IS DISTINCT FROM (NEW."last_reviewed_by_id") OR OLD."line" IS DISTINCT FROM (NEW."line") OR OLD."mitigated" IS DISTINCT FROM (NEW."mitigated") OR OLD."mitigated_by_id" IS DISTINCT FROM (NEW."mitigated_by_id") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."nb_occurences" IS DISTINCT FROM (NEW."nb_occurences") OR OLD."numerical_severity" IS DISTINCT FROM (NEW."numerical_severity") OR OLD."out_of_scope" IS DISTINCT FROM (NEW."out_of_scope") OR OLD."param" IS DISTINCT FROM (NEW."param") OR OLD."payload" IS DISTINCT FROM (NEW."payload") OR OLD."planned_remediation_date" IS DISTINCT FROM (NEW."planned_remediation_date") OR OLD."planned_remediation_version" IS DISTINCT FROM (NEW."planned_remediation_version") OR OLD."publish_date" IS DISTINCT FROM (NEW."publish_date") OR OLD."ransomware_used" IS DISTINCT FROM (NEW."ransomware_used") OR OLD."refs" IS DISTINCT FROM (NEW."refs") OR OLD."reporter_id" IS DISTINCT FROM (NEW."reporter_id") OR OLD."review_requested_by_id" IS DISTINCT FROM (NEW."review_requested_by_id") OR OLD."risk_accepted" IS DISTINCT FROM (NEW."risk_accepted") OR OLD."sast_sink_object" IS DISTINCT FROM (NEW."sast_sink_object") OR OLD."sast_source_file_path" IS DISTINCT FROM (NEW."sast_source_file_path") OR OLD."sast_source_line" IS DISTINCT FROM (NEW."sast_source_line") OR OLD."sast_source_object" IS DISTINCT FROM (NEW."sast_source_object") OR OLD."scanner_confidence" IS DISTINCT FROM (NEW."scanner_confidence") OR OLD."service" IS DISTINCT FROM (NEW."service") OR OLD."severity" IS DISTINCT FROM (NEW."severity") OR OLD."severity_justification" IS DISTINCT FROM (NEW."severity_justification") OR OLD."sla_expiration_date" IS DISTINCT FROM (NEW."sla_expiration_date") OR OLD."sla_start_date" IS DISTINCT FROM (NEW."sla_start_date") OR OLD."sonarqube_issue_id" IS DISTINCT FROM (NEW."sonarqube_issue_id") OR OLD."static_finding" IS DISTINCT FROM (NEW."static_finding") OR OLD."steps_to_reproduce" IS DISTINCT FROM (NEW."steps_to_reproduce") OR OLD."test_id" IS DISTINCT FROM (NEW."test_id") OR OLD."thread_id" IS DISTINCT FROM (NEW."thread_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."under_defect_review" IS DISTINCT FROM (NEW."under_defect_review") OR OLD."under_review" IS DISTINCT FROM (NEW."under_review") OR OLD."unique_id_from_tool" IS DISTINCT FROM (NEW."unique_id_from_tool") OR OLD."url" IS DISTINCT FROM (NEW."url") OR OLD."verified" IS DISTINCT FROM (NEW."verified") OR OLD."vuln_id_from_tool" IS DISTINCT FROM (NEW."vuln_id_from_tool"))', func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_decision", "auto_triage_reason", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."auto_triage_decision", NEW."auto_triage_reason", NEW."auto_triaged_at", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='b842ddada61a90333e3f42fedfccd5b50beee958', operation='UPDATE', pgid='pgtrigger_update_update_92175', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_decision", "auto_triage_reason", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (OLD."active", OLD."auto_triage_decision", OLD."auto_triage_reason", OLD."auto_triaged_at", OLD."component_name", OLD."component_version", OLD."created", OLD."cve", OLD."cvssv3", OLD."cvssv3_score", OLD."cvssv4", OLD."cvssv4_score", OLD."cwe", OLD."date", OLD."defect_review_requested_by_id", OLD."description", OLD."duplicate", OLD."duplicate_finding_id", OLD."dynamic_finding", OLD."effort_for_fixing", OLD."epss_percentile", OLD."epss_score", OLD."false_p", OLD."file_path", OLD."fix_available", OLD."hash_code", OLD."id", OLD."impact", OLD."is_mitigated", OLD."kev_date", OLD."known_exploited", OLD."last_reviewed", OLD."last_reviewed_by_id", OLD."last_status_update", OLD."line", OLD."mitigated", OLD."mitigated_by_id", OLD."mitigation", OLD."nb_occurences", OLD."numerical_severity", OLD."out_of_scope", OLD."param", OLD."payload", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."planned_remediation_date", OLD."planned_remediation_version", OLD."publish_date", OLD."ransomware_used", OLD."refs", OLD."reporter_id", OLD."review_requested_by_id", OLD."risk_accepted", OLD."sast_sink_object", OLD."sast_source_file_path", OLD."sast_source_line", OLD."sast_source_object", OLD."scanner_confidence", OLD."service", OLD."severity", OLD."severity_justification", OLD."sla_expiration_date", OLD."sla_start_date", OLD."sonarqube_issue_id", OLD."static_finding", OLD."steps_to_reproduce", OLD."test_id", OLD."thread_id", OLD."title", OLD."under_defect_review", OLD."under_review", OLD."unique_id_from_tool", OLD."url", OLD."verified", OLD."vuln_id_from_tool"); RETURN NULL;', hash='bc90c37daf9fdfe427c85eee8038a3d9c6a976b0', operation='DELETE', pgid='pgtrigger_delete_delete_72933', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_productevent" ("active_contributors_90d", "active_prs_30d", "async_updating", "business_criticality", "codeowners_content", "consistent_commit_pattern", "created", "days_since_last_commit", "description", "disable_sla_breach_notifications", "enable_full_risk_acceptance", "enable_product_tag_inheritance", "enable_simple_risk_acceptance", "external_audience", "github_repo_id", "github_url", "has_api_specs", "has_branch_protection", "has_ci_cd", "has_codeowners", "has_database_migrations", "has_dependabot_activity", "has_dependency_scanning", "has_deployment_scripts", "has_dockerfile", "has_documentation", "has_environments", "has_gitleaks_config", "has_kubernetes_config", "has_monitoring_config", "has_procfile", "has_releases", "has_sast_config", "has_secret_scanning", "has_security_md", "has_security_scanning", "has_ssl_config", "has_terraform", "has_tests", "id", "internet_accessible", "is_monorepo", "is_repository_placeholder", "last_commit_date", "lifecycle", "multiple_contributors", "name", "origin", "ownership_confidence", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "primary_framework", "primary_language", "prod_numeric_grade", "prod_type_id", "product_manager_id", "readme_length", "readme_summary", "recent_commits_30d", "recent_releases_90d", "revenue", "sla_configuration_id", "team_manager_id", "technical_contact_id", "tid", "updated", "user_records") VALUES (NEW."active_contributors_90d", NEW."active_prs_30d", NEW."async_updating", NEW."business_criticality", NEW."codeowners_content", NEW."consistent_commit_pattern", NEW."created", NEW."days_since_last_commit", NEW."description", NEW."disable_sla_breach_notifications", NEW."enable_full_risk_acceptance", NEW."enable_product_tag_inheritance", NEW."enable_simple_risk_acceptance", NEW."external_audience", NEW."github_repo_id", NEW."github_url", NEW."has_api_specs", NEW."has_branch_protection", NEW."has_ci_cd", NEW."has_codeowners", NEW."has_database_migrations", NEW."has_dependabot_activity", NEW."has_dependency_scanning", NEW."has_deployment_scripts", NEW."has_dockerfile", NEW."has_documentation", NEW."has_environments", NEW."has_gitleaks_config", NEW."has_kubernetes_config", NEW."has_monitoring_config", NEW."has_procfile", NEW."has_releases", NEW."has_sast_config", NEW."has_secret_scanning", NEW."has_security_md", NEW."has_security_scanning", NEW."has_ssl_config", NEW."has_terraform", NEW."has_tests", NEW."id", NEW."internet_accessible", NEW."is_monorepo", NEW."is_repository_placeholder", NEW."last_commit_date", NEW."lifecycle", NEW."multiple_contributors", NEW."name", NEW."origin", NEW."ownership_confidence", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform", NEW."primary_framework", NEW."primary_language", NEW."prod_numeric_grade", NEW."prod_type_id", NEW."product_manager_id", NEW."readme_length", NEW."readme_summary", NEW."recent_commits_30d", NEW."recent_releases_90d", NEW."revenue", NEW."sla_configuration_id", NEW."team_manager_id", NEW."technical_contact_id", NEW."tid", NEW."updated", NEW."user_records"); RETURN NULL;', hash='446a01b693518fad24eb237ebd2d6a1175507b72', operation='INSERT', pgid='pgtrigger_insert_insert_d5d32', table='dojo_product', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active_contributors_90d" IS DISTINCT FROM (NEW."active_contributors_90d") OR OLD."active_prs_30d" IS DISTINCT FROM (NEW."active_prs_30d") OR OLD."async_updating" IS DISTINCT FROM (NEW."async_updating") OR OLD."business_criticality" IS DISTINCT FROM (NEW."business_criticality") OR OLD."codeowners_content" IS DISTINCT FROM (NEW."codeowners_content") OR OLD."consistent_commit_pattern" IS DISTINCT FROM (NEW."consistent_commit_pattern") OR OLD."days_since_last_commit" IS DISTINCT FROM (NEW."days_since_last_commit") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."disable_sla_breach_notifications" IS DISTINCT FROM (NEW."disable_sla_breach_notifications") OR OLD."enable_full_risk_acceptance" IS DISTINCT FROM (NEW."enable_full_risk_acceptance") OR OLD."enable_product_tag_inheritance" IS DISTINCT FROM (NEW."enable_product_tag_inheritance") OR OLD."enable_simple_risk_acceptance" IS DISTINCT FROM (NEW."enable_simple_risk_acceptance") OR OLD."external_audience" IS DISTINCT FROM (NEW."external_audience") OR OLD."github_repo_id" IS DISTINCT FROM (NEW."github_repo_id") OR OLD."github_url" IS DISTINCT FROM (NEW."github_url") OR OLD."has_api_specs" IS DISTINCT FROM (NEW."has_api_specs") OR OLD."has_branch_protection" IS DISTINCT FROM (NEW."has_branch_protection") OR OLD."has_ci_cd" IS DISTINCT FROM (NEW."has_ci_cd") OR OLD."has_codeowners" IS DISTINCT FROM (NEW."has_codeowners") OR OLD."has_database_migrations" IS DISTINCT FROM (NEW."has_database_migrations") OR OLD."has_dependabot_activity" IS DISTINCT FROM (NEW."has_dependabot_activity") OR OLD."has_dependency_scanning" IS DISTINCT FROM (NEW."has_dependency_scanning") OR OLD."has_deployment_scripts" IS DISTINCT FROM (NEW."has_deployment_scripts") OR OLD."has_dockerfile" IS DISTINCT FROM (NEW."has_dockerfile") OR OLD."has_documentation" IS DISTINCT FROM (NEW."has_documentation") OR OLD."has_environments" IS DISTINCT FROM (NEW."has_environments") OR OLD."has_gitleaks_config" IS DISTINCT FROM (NEW."has_gitleaks_config") OR OLD."has_kubernetes_config" IS DISTINCT FROM (NEW."has_kubernetes_config") OR OLD."has_monitoring_config" IS DISTINCT FROM (NEW."has_monitoring_config") OR OLD."has_procfile" IS DISTINCT FROM (NEW."has_procfile") OR OLD."has_releases" IS DISTINCT FROM (NEW."has_releases") OR OLD."has_sast_config" IS DISTINCT FROM (NEW."has_sast_config") OR OLD."has_secret_scanning" IS DISTINCT FROM (NEW."has_secret_scanning") OR OLD."has_security_md" IS DISTINCT FROM (NEW."has_security_md") OR OLD."has_security_scanning" IS DISTINCT FROM (NEW."has_security_scanning") OR OLD."has_ssl_config" IS DISTINCT FROM (NEW."has_ssl_config") OR OLD."has_terraform" IS DISTINCT FROM (NEW."has_terraform") OR OLD."has_tests" IS DISTINCT FROM (NEW."has_tests") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."internet_accessible" IS DISTINCT FROM (NEW."internet_accessible") OR OLD."is_monorepo" IS DISTINCT FROM (NEW."is_monorepo") OR OLD."is_repository_placeholder" IS DISTINCT FROM (NEW."is_repository_placeholder") OR OLD."last_commit_date" IS DISTINCT FROM (NEW."last_commit_date") OR OLD."lifecycle" IS DISTINCT FROM (NEW."lifecycle") OR OLD."multiple_contributors" IS DISTINCT FROM (NEW."multiple_contributors") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."origin" IS DISTINCT FROM (NEW."origin") OR OLD."ownership_confidence" IS DISTINCT FROM (NEW."ownership_confidence") OR OLD."platform" IS DISTINCT FROM (NEW."platform") OR OLD."primary_framework" IS DISTINCT FROM (NEW."primary_framework") OR OLD."primary_language" IS DISTINCT FROM (NEW."primary_language") OR OLD."prod_numeric_grade" IS DISTINCT FROM (NEW."prod_numeric_grade") OR OLD."prod_type_id" IS DISTINCT FROM (NEW."prod_type_id") OR OLD."product_manager_id" IS DISTINCT FROM (NEW."product_manager_id") OR OLD."readme_length" IS DISTINCT FROM (NEW."readme_length") OR OLD."readme_summary" IS DISTINCT FROM (NEW."readme_summary") OR OLD."recent_commits_30d" IS DISTINCT FROM (NEW."recent_commits_30d") OR OLD."recent_releases_90d" IS DISTINCT FROM (NEW."recent_releases_90d") OR OLD."revenue" IS DISTINCT FROM (NEW."revenue") OR OLD."sla_configuration_id" IS DISTINCT FROM (NEW."sla_configuration_id") OR OLD."team_manager_id" IS DISTINCT FROM (NEW."team_manager_id") OR OLD."technical_contact_id" IS DISTINCT FROM (NEW."technical_contact_id") OR OLD."tid" IS DISTINCT FROM (NEW."tid") OR OLD."user_records" IS DISTINCT FROM (NEW."user_records"))', func='INSERT INTO "dojo_productevent" ("active_contributors_90d", "active_prs_30d", "async_updating", "business_criticality", "codeowners_content", "consistent_commit_pattern", "created", "days_since_last_commit", "description", "disable_sla_breach_notifications", "enable_full_risk_acceptance", "enable_product_tag_inheritance", "enable_simple_risk_acceptance", "external_audience", "github_repo_id", "github_url", "has_api_specs", "has_branch_protection", "has_ci_cd", "has_codeowners", "has_database_migrations", "has_dependabot_activity", "has_dependency_scanning", "has_deployment_scripts", "has_dockerfile", "has_documentation", "has_environments", "has_gitleaks_config", "has_kubernetes_config", "has_monitoring_config", "has_procfile", "has_releases", "has_sast_config", "has_secret_scanning", "has_security_md", "has_security_scanning", "has_ssl_config", "has_terraform", "has_tests", "id", "internet_accessible", "is_monorepo", "is_repository_placeholder", "last_commit_date", "lifecycle", "multiple_contributors", "name", "origin", "ownership_confidence", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "primary_framework", "primary_language", "prod_numeric_grade", "prod_type_id", "product_manager_id", "readme_length", "readme_summary", "recent_commits_30d", "recent_releases_90d", "revenue", "sla_configuration_id", "team_manager_id", "technical_contact_id", "tid", "updated", "user_records") VALUES (NEW."active_contributors_90d", NEW."active_prs_30d", NEW."async_updating", NEW."business_criticality", NEW."codeowners_content", NEW."consistent_commit_pattern", NEW."created", NEW."days_since_last_commit", NEW."description", NEW."disable_sla_breach_notifications", NEW."enable_full_risk_acceptance", NEW."enable_product_tag_inheritance", NEW."enable_simple_risk_acceptance", NEW."external_audience", NEW."github_repo_id", NEW."github_url", NEW."has_api_specs", NEW."has_branch_protection", NEW."has_ci_cd", NEW."has_codeowners", NEW."has_database_migrations", NEW."has_dependabot_activity", NEW."has_dependency_scanning", NEW."has_deployment_scripts", NEW."has_dockerfile", NEW."has_documentation", NEW."has_environments", NEW."has_gitleaks_config", NEW."has_kubernetes_config", NEW."has_monitoring_config", NEW."has_procfile", NEW."has_releases", NEW."has_sast_config", NEW."has_secret_scanning", NEW."has_security_md", NEW."has_security_scanning", NEW."has_ssl_config", NEW."has_terraform", NEW."has_tests", NEW."id", NEW."internet_accessible", NEW."is_monorepo", NEW."is_repository_placeholder", NEW."last_commit_date", NEW."lifecycle", NEW."multiple_contributors", NEW."name", NEW."origin", NEW."ownership_confidence", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform", NEW."primary_framework", NEW."primary_language", NEW."prod_numeric_grade", NEW."prod_type_id", NEW."product_manager_id", NEW."readme_length", NEW."readme_summary", NEW."recent_commits_30d", NEW."recent_releases_90d", NEW."revenue", NEW."sla_configuration_id", NEW."team_manager_id", NEW."technical_contact_id", NEW."tid", NEW."updated", NEW."user_records"); RETURN NULL;', hash='a6bdb4ceecd417f205adbd06ba991a37d0cf4876', operation='UPDATE', pgid='pgtrigger_update_update_e7040', table='dojo_product', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='product',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_productevent" ("active_contributors_90d", "active_prs_30d", "async_updating", "business_criticality", "codeowners_content", "consistent_commit_pattern", "created", "days_since_last_commit", "description", "disable_sla_breach_notifications", "enable_full_risk_acceptance", "enable_product_tag_inheritance", "enable_simple_risk_acceptance", "external_audience", "github_repo_id", "github_url", "has_api_specs", "has_branch_protection", "has_ci_cd", "has_codeowners", "has_database_migrations", "has_dependabot_activity", "has_dependency_scanning", "has_deployment_scripts", "has_dockerfile", "has_documentation", "has_environments", "has_gitleaks_config", "has_kubernetes_config", "has_monitoring_config", "has_procfile", "has_releases", "has_sast_config", "has_secret_scanning", "has_security_md", "has_security_scanning", "has_ssl_config", "has_terraform", "has_tests", "id", "internet_accessible", "is_monorepo", "is_repository_placeholder", "last_commit_date", "lifecycle", "multiple_contributors", "name", "origin", "ownership_confidence", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "primary_framework", "primary_language", "prod_numeric_grade", "prod_type_id", "product_manager_id", "readme_length", "readme_summary", "recent_commits_30d", "recent_releases_90d", "revenue", "sla_configuration_id", "team_manager_id", "technical_contact_id", "tid", "updated", "user_records") VALUES (OLD."active_contributors_90d", OLD."active_prs_30d", OLD."async_updating", OLD."business_criticality", OLD."codeowners_content", OLD."consistent_commit_pattern", OLD."created", OLD."days_since_last_commit", OLD."description", OLD."disable_sla_breach_notifications", OLD."enable_full_risk_acceptance", OLD."enable_product_tag_inheritance", OLD."enable_simple_risk_acceptance", OLD."external_audience", OLD."github_repo_id", OLD."github_url", OLD."has_api_specs", OLD."has_branch_protection", OLD."has_ci_cd", OLD."has_codeowners", OLD."has_database_migrations", OLD."has_dependabot_activity", OLD."has_dependency_scanning", OLD."has_deployment_scripts", OLD."has_dockerfile", OLD."has_documentation", OLD."has_environments", OLD."has_gitleaks_config", OLD."has_kubernetes_config", OLD."has_monitoring_config", OLD."has_procfile", OLD."has_releases", OLD."has_sast_config", OLD."has_secret_scanning", OLD."has_security_md", OLD."has_security_scanning", OLD."has_ssl_config", OLD."has_terraform", OLD."has_tests", OLD."id", OLD."internet_accessible", OLD."is_monorepo", OLD."is_repository_placeholder", OLD."last_commit_date", OLD."lifecycle", OLD."multiple_contributors", OLD."name", OLD."origin", OLD."ownership_confidence", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform", OLD."primary_framework", OLD."primary_language", OLD."prod_numeric_grade", OLD."prod_type_id", OLD."product_manager_id", OLD."readme_length", OLD."readme_summary", OLD."recent_commits_30d", OLD."recent_releases_90d", OLD."revenue", OLD."sla_configuration_id", OLD."team_manager_id", OLD."technical_contact_id", OLD."tid", OLD."updated", OLD."user_records"); RETURN NULL;', hash='97087a1914d908e20b8ef7e7bba1470ad2515d90', operation='DELETE', pgid='pgtrigger_delete_delete_064dd', table='dojo_product', when='AFTER')),
        ),
        migrations.AddField(
            model_name='repository',
            name='product',
            field=models.ForeignKey(help_text='Primary product/application this repository belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='dojo.product', verbose_name='Primary Product'),
        ),
        migrations.AddField(
            model_name='repository',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Additional products that share this repository (e.g., shared libraries)', related_name='shared_repositories', to='dojo.product', verbose_name='Related Products'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['github_repo_id'], name='dojo_reposi_github__c95dda_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['product'], name='dojo_reposi_product_c67c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['tier'], name='dojo_reposi_tier_0f7275_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['last_alert_sync'], name='dojo_reposi_last_al_02ce16_idx'),
        ),
    ]
