# Generated by Django 5.1.14 on 2025-11-14 06:34

from django.db import migrations


def copy_product_to_repository(apps, schema_editor):
    """
    Migrate Products with github_repo_id to Repository model.

    This data migration is part of Phase 1 of the GitHub Security Alerts hierarchy:
    - Creates Repository records from Products that have github_repo_id
    - Copies all 47 enrichment fields from Product to Repository
    - Links Repository to Product via ForeignKey
    - Marks migrated Products with is_repository_placeholder=True
    """
    Product = apps.get_model('dojo', 'Product')
    Repository = apps.get_model('dojo', 'Repository')

    # Find all Products with github_repo_id (these are 1:1 repository mappings)
    products_with_repos = Product.objects.filter(
        github_repo_id__isnull=False
    ).exclude(github_repo_id=0)

    repositories_created = 0

    for product in products_with_repos:
        # Check if Repository already exists for this github_repo_id
        if Repository.objects.filter(github_repo_id=product.github_repo_id).exists():
            continue

        # Create Repository from Product
        repository = Repository.objects.create(
            # Core identification
            name=product.name,
            github_repo_id=product.github_repo_id,
            github_url=product.github_url or '',

            # Product relationship
            product=product,

            # Repository Activity Tracking (3 fields)
            last_commit_date=product.last_commit_date,
            active_contributors_90d=product.active_contributors_90d or 0,
            days_since_last_commit=product.days_since_last_commit,

            # Repository Metadata (4 fields)
            readme_summary=product.readme_summary or '',
            readme_length=product.readme_length or 0,
            primary_language=product.primary_language or '',
            primary_framework=product.primary_framework or '',

            # Ownership Tracking (2 fields)
            codeowners_content=product.codeowners_content or '',
            ownership_confidence=product.ownership_confidence or 0,

            # Binary Signals: Deployment Indicators (6 fields)
            has_dockerfile=product.has_dockerfile or False,
            has_kubernetes_config=product.has_kubernetes_config or False,
            has_ci_cd=product.has_ci_cd or False,
            has_terraform=product.has_terraform or False,
            has_deployment_scripts=product.has_deployment_scripts or False,
            has_procfile=product.has_procfile or False,

            # Binary Signals: Production Readiness (6 fields)
            has_environments=product.has_environments or False,
            has_releases=product.has_releases or False,
            has_branch_protection=product.has_branch_protection or False,
            has_monitoring_config=product.has_monitoring_config or False,
            has_ssl_config=product.has_ssl_config or False,
            has_database_migrations=product.has_database_migrations or False,

            # Binary Signals: Active Development (6 fields)
            recent_commits_30d=product.recent_commits_30d or False,
            active_prs_30d=product.active_prs_30d or False,
            multiple_contributors=product.multiple_contributors or False,
            has_dependabot_activity=product.has_dependabot_activity or False,
            recent_releases_90d=product.recent_releases_90d or False,
            consistent_commit_pattern=product.consistent_commit_pattern or False,

            # Binary Signals: Code Organization (6 fields)
            has_tests=product.has_tests or False,
            has_documentation=product.has_documentation or False,
            has_api_specs=product.has_api_specs or False,
            has_codeowners=product.has_codeowners or False,
            has_security_md=product.has_security_md or False,
            is_monorepo=product.is_monorepo or False,

            # Binary Signals: Security Maturity (5 fields)
            has_security_scanning=product.has_security_scanning or False,
            has_secret_scanning=product.has_secret_scanning or False,
            has_dependency_scanning=product.has_dependency_scanning or False,
            has_gitleaks_config=product.has_gitleaks_config or False,
            has_sast_config=product.has_sast_config or False,

            # Computed tier classification (map business_criticality to tier)
            tier=_map_criticality_to_tier(product.business_criticality) if hasattr(product, 'business_criticality') else 'tier4',
        )

        # Mark Product as repository placeholder
        product.is_repository_placeholder = True
        product.save(update_fields=['is_repository_placeholder'])

        repositories_created += 1

    if repositories_created > 0:
        print(f"Created {repositories_created} Repository records from Products")


def _map_criticality_to_tier(criticality):
    """Map Product.business_criticality to Repository.tier"""
    mapping = {
        'very high': 'tier1',
        'high': 'tier2',
        'medium': 'tier3',
        'low': 'tier4',
        'none': 'tier4',
    }
    return mapping.get(criticality, 'tier4')


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting Repository records and unmarking Products.
    """
    Product = apps.get_model('dojo', 'Product')
    Repository = apps.get_model('dojo', 'Repository')

    # Delete all Repository records
    count = Repository.objects.all().count()
    Repository.objects.all().delete()

    # Unmark all Products
    Product.objects.filter(is_repository_placeholder=True).update(
        is_repository_placeholder=False
    )

    print(f"Deleted {count} Repository records and unmarked Products")


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0247_repository_remove_finding_insert_insert_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_product_to_repository, reverse_migration),
    ]
