# Generated by Django 5.1.14 on 2025-11-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0248_copy_product_to_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAlertSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependabot_last_sync', models.DateTimeField(blank=True, help_text='Last successful sync of Dependabot alerts', null=True, verbose_name='Dependabot Last Sync')),
                ('codeql_last_sync', models.DateTimeField(blank=True, help_text='Last successful sync of CodeQL alerts', null=True, verbose_name='CodeQL Last Sync')),
                ('secret_scanning_last_sync', models.DateTimeField(blank=True, help_text='Last successful sync of Secret Scanning alerts', null=True, verbose_name='Secret Scanning Last Sync')),
                ('dependabot_alerts_fetched', models.IntegerField(default=0, help_text='Total Dependabot alerts fetched in last sync', verbose_name='Dependabot Alerts Fetched')),
                ('codeql_alerts_fetched', models.IntegerField(default=0, help_text='Total CodeQL alerts fetched in last sync', verbose_name='CodeQL Alerts Fetched')),
                ('secret_scanning_alerts_fetched', models.IntegerField(default=0, help_text='Total Secret Scanning alerts fetched in last sync', verbose_name='Secret Scanning Alerts Fetched')),
                ('last_sync_error', models.TextField(blank=True, help_text='Error message from last sync attempt (if any)', verbose_name='Last Sync Error')),
                ('last_sync_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync Error Time')),
                ('last_rate_limit_hit', models.DateTimeField(blank=True, help_text='Last time we hit GitHub rate limit for this repo', null=True, verbose_name='Last Rate Limit Hit')),
                ('full_sync_completed', models.BooleanField(default=False, help_text='True if initial full sync has been completed', verbose_name='Full Sync Completed')),
                ('sync_enabled', models.BooleanField(default=True, help_text='False to skip this repository during sync', verbose_name='Sync Enabled')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_sync_status', to='dojo.repository', verbose_name='Repository')),
            ],
            options={
                'verbose_name': 'GitHub Alert Sync Status',
                'verbose_name_plural': 'GitHub Alert Sync Statuses',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='GitHubAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('dependabot', 'Dependabot Alert'), ('codeql', 'CodeQL Alert'), ('secret_scanning', 'Secret Scanning Alert')], help_text='Type of GitHub security alert', max_length=20, verbose_name='Alert Type')),
                ('github_alert_id', models.CharField(help_text="GitHub's unique identifier for this alert (alert number or node ID)", max_length=100, verbose_name='GitHub Alert ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('fixed', 'Fixed')], default='open', help_text='Current state of the alert in GitHub', max_length=20, verbose_name='State')),
                ('severity', models.CharField(blank=True, help_text='Alert severity (Critical, High, Medium, Low)', max_length=20, verbose_name='Severity')),
                ('title', models.CharField(help_text='Alert title or description', max_length=500, verbose_name='Title')),
                ('html_url', models.URLField(help_text='Direct link to alert on GitHub', max_length=600, verbose_name='GitHub URL')),
                ('created_at', models.DateTimeField(help_text='When alert was created in GitHub', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(help_text='Last update time in GitHub', verbose_name='Updated At')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='When alert was dismissed in GitHub', null=True, verbose_name='Dismissed At')),
                ('fixed_at', models.DateTimeField(blank=True, help_text='When alert was marked as fixed in GitHub', null=True, verbose_name='Fixed At')),
                ('cve', models.CharField(blank=True, help_text='CVE identifier (for Dependabot alerts)', max_length=50, verbose_name='CVE')),
                ('package_name', models.CharField(blank=True, help_text='Affected package name (for Dependabot alerts)', max_length=255, verbose_name='Package Name')),
                ('package_ecosystem', models.CharField(blank=True, help_text='Package ecosystem: npm, pip, maven, etc.', max_length=50, verbose_name='Package Ecosystem')),
                ('vulnerable_version', models.CharField(blank=True, help_text='Current vulnerable version', max_length=100, verbose_name='Vulnerable Version')),
                ('patched_version', models.CharField(blank=True, help_text='Fixed version available', max_length=100, verbose_name='Patched Version')),
                ('cwe', models.CharField(blank=True, help_text='CWE identifier (for CodeQL alerts)', max_length=50, verbose_name='CWE')),
                ('rule_id', models.CharField(blank=True, help_text='CodeQL rule identifier', max_length=200, verbose_name='Rule ID')),
                ('file_path', models.CharField(blank=True, help_text='Path to affected file', max_length=1000, verbose_name='File Path')),
                ('start_line', models.IntegerField(blank=True, help_text='Starting line number', null=True, verbose_name='Start Line')),
                ('end_line', models.IntegerField(blank=True, help_text='Ending line number', null=True, verbose_name='End Line')),
                ('secret_type', models.CharField(blank=True, help_text='Type of secret detected (for Secret Scanning alerts)', max_length=200, verbose_name='Secret Type')),
                ('raw_data', models.JSONField(default=dict, help_text='Complete JSON response from GitHub API for this alert', verbose_name='Raw GitHub Data')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last time this alert was synced from GitHub', verbose_name='Last Synced')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created in DefectDojo')),
                ('finding', models.ForeignKey(blank=True, help_text='DefectDojo Finding created from this alert (Phase 3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_alerts', to='dojo.finding', verbose_name='Related Finding')),
                ('repository', models.ForeignKey(help_text='Repository this alert belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='github_alerts', to='dojo.repository', verbose_name='Repository')),
            ],
            options={
                'verbose_name': 'GitHub Alert',
                'verbose_name_plural': 'GitHub Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'alert_type'], name='dojo_github_reposit_e10bfe_idx'), models.Index(fields=['state'], name='dojo_github_state_faea9a_idx'), models.Index(fields=['severity'], name='dojo_github_severit_18dc79_idx'), models.Index(fields=['created_at'], name='dojo_github_created_27ba7d_idx')],
                'unique_together': {('repository', 'alert_type', 'github_alert_id')},
            },
        ),
    ]
