# Generated by Django 5.1.14 on 2025-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0249_githubalertsync_githubalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubalert',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='When alert was created in GitHub', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='githubalert',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Last update time in GitHub', null=True, verbose_name='Updated At'),
        ),
    ]
