# Generated by Django 5.1.14 on 2025-11-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0250_alter_githubalert_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubalert',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the alert', verbose_name='Description'),
        ),
    ]
