# Generated by Django 5.1.14 on 2025-11-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0252_product_migration_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInsightConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_config', models.JSONField(default=list, help_text='JSON array of widget configurations with insight_id, order, size, pinned, auto_refresh, and filters', verbose_name='Widget Configuration')),
                ('widget_count', models.IntegerField(default=10, help_text='Number of widgets to display on dashboard (pinned widgets bypass this limit)', verbose_name='Widget Count')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this dashboard configuration', on_delete=django.db.models.deletion.CASCADE, related_name='github_insight_config', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'GitHub Insight Configuration',
                'verbose_name_plural': 'GitHub Insight Configurations',
                'db_table': 'github_insight_configuration',
            },
        ),
    ]
