# Generated by Django 5.1.14 on 2025-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0256_remove_product_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubSyncConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_token', models.CharField(help_text='GitHub PAT with repo:read permissions (stored encrypted)', max_length=255, verbose_name='GitHub Personal Access Token')),
                ('account_type', models.CharField(choices=[('organization', 'Organization'), ('user', 'Personal Account')], default='organization', help_text='Type of GitHub account to sync (organization or personal account)', max_length=20, verbose_name='Account Type')),
                ('account_name', models.CharField(help_text='GitHub organization or user account name', max_length=255, verbose_name='Account Name')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Enable automatic repository synchronization', verbose_name='Auto-Sync Enabled')),
                ('sync_schedule', models.CharField(choices=[('manual', 'Manual (No Auto-Sync)'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', help_text='Frequency of automatic synchronization', max_length=20, verbose_name='Sync Schedule')),
                ('incremental_sync', models.BooleanField(default=True, help_text='Only sync repositories updated since last sync (recommended)', verbose_name='Incremental Sync')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of last successful synchronization', null=True, verbose_name='Last Sync')),
                ('last_sync_status', models.CharField(blank=True, help_text='Status of last sync: success, failed, partial', max_length=20, null=True, verbose_name='Last Sync Status')),
                ('last_sync_error', models.TextField(blank=True, help_text='Error message from last failed sync', verbose_name='Last Sync Error')),
                ('total_repos_synced', models.IntegerField(default=0, help_text='Cumulative count of repositories synced', verbose_name='Total Repositories Synced')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Sync Configuration',
                'verbose_name_plural': 'GitHub Sync Configurations',
                'db_table': 'github_sync_configuration',
            },
        ),
    ]
