# Generated by Django 5.1.14 on 2025-11-22 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0257_github_sync_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='active_webhooks_count',
            field=models.IntegerField(default=0, help_text='Number of active webhooks configured', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Active Webhooks'),
        ),
        migrations.AddField(
            model_name='repository',
            name='commit_count',
            field=models.IntegerField(default=0, help_text='Total number of commits in default branch', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Commits'),
        ),
        migrations.AddField(
            model_name='repository',
            name='has_webhooks',
            field=models.BooleanField(default=False, help_text='Whether repository has any webhooks configured', verbose_name='Has Webhooks'),
        ),
        migrations.AddField(
            model_name='repository',
            name='open_issues_count',
            field=models.IntegerField(default=0, help_text='Number of currently open issues', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Open Issues'),
        ),
        migrations.AddField(
            model_name='repository',
            name='open_pr_count',
            field=models.IntegerField(default=0, help_text='Number of currently open pull requests', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Open Pull Requests'),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_cadence',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('2 Hours', '2 Hours'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Inactive', 'Inactive'), ('Unknown', 'Unknown')], default='Inactive', help_text='Baseline webhook delivery frequency based on last 25 events', max_length=20, verbose_name='Webhook Cadence'),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_types',
            field=models.JSONField(blank=True, default=list, help_text='Detected webhook integration types (JIRA, CI/CD, Slack, etc.)', verbose_name='Webhook Types'),
        ),
    ]
