# Generated by Django 5.1.14 on 2025-11-24 - Priority Scoring Phase 1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0258_repository_active_webhooks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='priority_score',
            field=models.IntegerField(
                default=0,
                db_index=True,
                verbose_name='Priority Score',
                help_text='Computed priority score combining tier, severity, and modifiers (0-1000+)'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_bucket',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('P0', 'Critical'),
                    ('P1', 'High'),
                    ('P2', 'Medium'),
                    ('P3', 'Low'),
                    ('P4', 'Minimal'),
                ],
                default='P3',
                db_index=True,
                verbose_name='Priority Bucket',
                help_text='Priority bucket based on score: P0 (>=500), P1 (300-499), P2 (150-299), P3 (50-149), P4 (<50)'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_calculated_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name='Priority Calculated At',
                help_text='Timestamp when priority score was last calculated'
            ),
        ),
    ]
