# Generated by Django 5.1.14 on 2025-11-24 - Triage Workflow Phase 2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0259_finding_priority_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='triage_state',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pending', 'Pending Triage'),
                    ('escalated', 'Escalated'),
                    ('assigned', 'Assigned'),
                    ('deferred', 'Deferred'),
                    ('accepted', 'Risk Accepted'),
                    ('dismissed', 'Dismissed'),
                ],
                default='pending',
                db_index=True,
                verbose_name='Triage State',
                help_text='Current triage workflow state'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_assigned_to',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                related_name='assigned_findings',
                verbose_name='Triage Assigned To',
                help_text='User assigned to triage this finding'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_due_date',
            field=models.DateField(
                null=True,
                blank=True,
                verbose_name='Triage Due Date',
                help_text='Due date for triage completion'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='triage_reason',
            field=models.TextField(
                blank=True,
                verbose_name='Triage Reason',
                help_text='Reason for triage decision'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='auto_triage_rule',
            field=models.CharField(
                max_length=100,
                blank=True,
                verbose_name='Auto-Triage Rule',
                help_text='Name of the auto-triage rule that was applied'
            ),
        ),
        migrations.AddField(
            model_name='finding',
            name='auto_triage_confidence',
            field=models.IntegerField(
                null=True,
                blank=True,
                verbose_name='Auto-Triage Confidence',
                help_text='Confidence score (0-100) of the auto-triage decision'
            ),
        ),
    ]
