# Generated by Django 5.1.14 on 2025-11-24 - Triage History Model Phase 2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0260_finding_triage_workflow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    max_length=20,
                    choices=[
                        ('created', 'Created'),
                        ('auto_triaged', 'Auto-Triaged'),
                        ('escalated', 'Escalated'),
                        ('assigned', 'Assigned'),
                        ('deferred', 'Deferred'),
                        ('accepted', 'Risk Accepted'),
                        ('dismissed', 'Dismissed'),
                        ('reopened', 'Reopened'),
                    ],
                    verbose_name='Action',
                    help_text='Type of triage action performed'
                )),
                ('previous_state', models.CharField(
                    max_length=20,
                    blank=True,
                    verbose_name='Previous State',
                    help_text='Triage state before this action'
                )),
                ('new_state', models.CharField(
                    max_length=20,
                    verbose_name='New State',
                    help_text='Triage state after this action'
                )),
                ('reason', models.TextField(
                    blank=True,
                    verbose_name='Reason',
                    help_text='Reason provided for the triage decision'
                )),
                ('rule_name', models.CharField(
                    max_length=100,
                    blank=True,
                    verbose_name='Rule Name',
                    help_text='Name of auto-triage rule that was applied (if auto-triaged)'
                )),
                ('confidence', models.IntegerField(
                    null=True,
                    blank=True,
                    verbose_name='Confidence',
                    help_text='Confidence score (0-100) of auto-triage decision'
                )),
                ('performed_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Performed At',
                    help_text='Timestamp when the action was performed'
                )),
                ('finding', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='triage_history',
                    to='dojo.finding',
                    verbose_name='Finding',
                    help_text='Finding this triage action applies to'
                )),
                ('performed_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Performed By',
                    help_text='User who performed the action (null for auto-triage)'
                )),
            ],
            options={
                'ordering': ['-performed_at'],
                'verbose_name': 'Triage History',
                'verbose_name_plural': 'Triage History',
            },
        ),
    ]
