# Generated by Django 5.1.14 on 2025-11-24 - Backfill triage_state Phase 2

from django.db import migrations


def backfill_triage_state(apps, schema_editor):
    """
    Backfill triage_state from existing flags and auto_triage_decision.

    Mapping priority (highest first):
    1. risk_accepted=True → 'accepted'
    2. under_review=True → 'assigned' (someone is actively working on it)
    3. auto_triage_decision='DISMISS' → 'dismissed'
    4. auto_triage_decision='ESCALATE' → 'escalated'
    5. auto_triage_decision='ACCEPT_RISK' → 'accepted'
    6. Everything else stays 'pending' (the default)

    Also backfills auto_triage_rule and auto_triage_confidence from auto_triage_reason.
    """
    Finding = apps.get_model('dojo', 'Finding')

    # 1. Risk accepted findings get 'accepted' state
    updated_risk = Finding.objects.filter(risk_accepted=True).update(triage_state='accepted')
    print(f"  Backfilled {updated_risk} risk_accepted findings to 'accepted'")

    # 2. Under review findings (not already risk_accepted) get 'assigned' state
    updated_review = Finding.objects.filter(
        under_review=True,
        risk_accepted=False  # Don't overwrite risk_accepted
    ).update(triage_state='assigned')
    print(f"  Backfilled {updated_review} under_review findings to 'assigned'")

    # 3. Auto-triaged DISMISS → 'dismissed'
    updated_dismiss = Finding.objects.filter(
        auto_triage_decision='DISMISS',
        risk_accepted=False,
        under_review=False
    ).update(triage_state='dismissed')
    print(f"  Backfilled {updated_dismiss} DISMISS auto-triaged findings to 'dismissed'")

    # 4. Auto-triaged ESCALATE → 'escalated'
    updated_escalate = Finding.objects.filter(
        auto_triage_decision='ESCALATE',
        risk_accepted=False,
        under_review=False
    ).update(triage_state='escalated')
    print(f"  Backfilled {updated_escalate} ESCALATE auto-triaged findings to 'escalated'")

    # 5. Auto-triaged ACCEPT_RISK → 'accepted' (if not already handled)
    updated_accept = Finding.objects.filter(
        auto_triage_decision='ACCEPT_RISK',
        risk_accepted=False,  # Manual risk_accepted takes precedence
        under_review=False
    ).update(triage_state='accepted')
    print(f"  Backfilled {updated_accept} ACCEPT_RISK auto-triaged findings to 'accepted'")

    # 6. Extract rule name and confidence from auto_triage_reason
    # Format: "reason text (Rule: rule_name, Confidence: 85%)"
    import re

    findings_with_auto_triage = Finding.objects.exclude(
        auto_triage_reason__isnull=True
    ).exclude(auto_triage_reason='')

    rule_pattern = re.compile(r'\(Rule: ([^,]+), Confidence: (\d+)%\)')
    extracted_count = 0

    for finding in findings_with_auto_triage.iterator():
        match = rule_pattern.search(finding.auto_triage_reason or '')
        if match:
            finding.auto_triage_rule = match.group(1)
            finding.auto_triage_confidence = int(match.group(2))
            finding.save(update_fields=['auto_triage_rule', 'auto_triage_confidence'])
            extracted_count += 1

    print(f"  Extracted rule/confidence from {extracted_count} auto-triaged findings")

    total_updated = updated_risk + updated_review + updated_dismiss + updated_escalate + updated_accept
    print(f"  Total findings with triage_state updated: {total_updated}")


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill by resetting triage_state to 'pending' and clearing extracted fields.
    """
    Finding = apps.get_model('dojo', 'Finding')

    # Reset all to pending
    Finding.objects.all().update(
        triage_state='pending',
        auto_triage_rule='',
        auto_triage_confidence=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0261_triage_history_model'),
    ]

    operations = [
        migrations.RunPython(backfill_triage_state, reverse_backfill),
    ]
