# Generated by Django 5.1.14 on 2025-11-25 20:07

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0262_backfill_triage_state'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='findingevent',
            name='auto_triage_confidence',
            field=models.IntegerField(blank=True, help_text='Confidence score (0-100) of the auto-triage decision', null=True, verbose_name='Auto-Triage Confidence'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='auto_triage_rule',
            field=models.CharField(blank=True, help_text='Name of the auto-triage rule that was applied', max_length=100, verbose_name='Auto-Triage Rule'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='priority_bucket',
            field=models.CharField(choices=[('P0', 'Critical'), ('P1', 'High'), ('P2', 'Medium'), ('P3', 'Low'), ('P4', 'Minimal')], default='P3', help_text='Priority bucket based on score: P0 (>=500), P1 (300-499), P2 (150-299), P3 (50-149), P4 (<50)', max_length=10, verbose_name='Priority Bucket'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='priority_calculated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when priority score was last calculated', null=True, verbose_name='Priority Calculated At'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Computed priority score combining tier, severity, and modifiers (0-1000+)', verbose_name='Priority Score'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='triage_assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, help_text='User assigned to triage this finding', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.dojo_user', verbose_name='Triage Assigned To'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='triage_due_date',
            field=models.DateField(blank=True, help_text='Due date for triage completion', null=True, verbose_name='Triage Due Date'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='triage_reason',
            field=models.TextField(blank=True, help_text='Reason for triage decision', verbose_name='Triage Reason'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='triage_state',
            field=models.CharField(choices=[('pending', 'Pending Triage'), ('escalated', 'Escalated'), ('assigned', 'Assigned'), ('deferred', 'Deferred'), ('accepted', 'Risk Accepted'), ('dismissed', 'Dismissed')], default='pending', help_text='Current triage workflow state', max_length=20, verbose_name='Triage State'),
        ),
        migrations.AddField(
            model_name='repository',
            name='clone_count_14d',
            field=models.IntegerField(default=0, help_text='Repository clones in last 14 days (requires push access)', verbose_name='Clone Count (14d)'),
        ),
        migrations.AddField(
            model_name='repository',
            name='consumption_tier_override',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1 - Critical'), ('tier2', 'Tier 2 - High'), ('tier3', 'Tier 3 - Medium'), ('tier4', 'Tier 4 - Low'), ('archived', 'Archived')], help_text='Tier override based on consumption (high consumption = higher tier)', max_length=10, null=True, verbose_name='Consumption Tier Override'),
        ),
        migrations.AddField(
            model_name='repository',
            name='dependent_repo_count',
            field=models.IntegerField(default=0, help_text='Number of internal repositories that depend on this one', verbose_name='Dependent Repositories'),
        ),
        migrations.AddField(
            model_name='repository',
            name='downstream_consumers',
            field=models.JSONField(blank=True, default=list, help_text='List of repo names that declare this as a dependency', verbose_name='Downstream Consumers'),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_shared_library',
            field=models.BooleanField(default=False, help_text='True if consumed by 5+ repositories', verbose_name='Is Shared Library'),
        ),
        migrations.AddField(
            model_name='repository',
            name='view_count_14d',
            field=models.IntegerField(default=0, help_text='Repository page views in last 14 days (requires push access)', verbose_name='View Count (14d)'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='triage_assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to triage this finding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to='dojo.dojo_user', verbose_name='Triage Assigned To'),
        ),
        migrations.AlterField(
            model_name='triagehistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for auto-triage)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.dojo_user', verbose_name='Performed By'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_confidence", "auto_triage_decision", "auto_triage_reason", "auto_triage_rule", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "priority_bucket", "priority_calculated_at", "priority_score", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "triage_assigned_to_id", "triage_due_date", "triage_reason", "triage_state", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."auto_triage_confidence", NEW."auto_triage_decision", NEW."auto_triage_reason", NEW."auto_triage_rule", NEW."auto_triaged_at", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."priority_bucket", NEW."priority_calculated_at", NEW."priority_score", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."triage_assigned_to_id", NEW."triage_due_date", NEW."triage_reason", NEW."triage_state", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='599a04b969f2e60727da0b80ace2457ab8cd8b2c', operation='INSERT', pgid='pgtrigger_insert_insert_2fbbb', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."auto_triage_confidence" IS DISTINCT FROM (NEW."auto_triage_confidence") OR OLD."auto_triage_decision" IS DISTINCT FROM (NEW."auto_triage_decision") OR OLD."auto_triage_reason" IS DISTINCT FROM (NEW."auto_triage_reason") OR OLD."auto_triage_rule" IS DISTINCT FROM (NEW."auto_triage_rule") OR OLD."auto_triaged_at" IS DISTINCT FROM (NEW."auto_triaged_at") OR OLD."component_name" IS DISTINCT FROM (NEW."component_name") OR OLD."component_version" IS DISTINCT FROM (NEW."component_version") OR OLD."cve" IS DISTINCT FROM (NEW."cve") OR OLD."cvssv3" IS DISTINCT FROM (NEW."cvssv3") OR OLD."cvssv3_score" IS DISTINCT FROM (NEW."cvssv3_score") OR OLD."cvssv4" IS DISTINCT FROM (NEW."cvssv4") OR OLD."cvssv4_score" IS DISTINCT FROM (NEW."cvssv4_score") OR OLD."cwe" IS DISTINCT FROM (NEW."cwe") OR OLD."date" IS DISTINCT FROM (NEW."date") OR OLD."defect_review_requested_by_id" IS DISTINCT FROM (NEW."defect_review_requested_by_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duplicate" IS DISTINCT FROM (NEW."duplicate") OR OLD."duplicate_finding_id" IS DISTINCT FROM (NEW."duplicate_finding_id") OR OLD."dynamic_finding" IS DISTINCT FROM (NEW."dynamic_finding") OR OLD."effort_for_fixing" IS DISTINCT FROM (NEW."effort_for_fixing") OR OLD."epss_percentile" IS DISTINCT FROM (NEW."epss_percentile") OR OLD."epss_score" IS DISTINCT FROM (NEW."epss_score") OR OLD."false_p" IS DISTINCT FROM (NEW."false_p") OR OLD."file_path" IS DISTINCT FROM (NEW."file_path") OR OLD."fix_available" IS DISTINCT FROM (NEW."fix_available") OR OLD."hash_code" IS DISTINCT FROM (NEW."hash_code") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."is_mitigated" IS DISTINCT FROM (NEW."is_mitigated") OR OLD."kev_date" IS DISTINCT FROM (NEW."kev_date") OR OLD."known_exploited" IS DISTINCT FROM (NEW."known_exploited") OR OLD."last_reviewed" IS DISTINCT FROM (NEW."last_reviewed") OR OLD."last_reviewed_by_id" IS DISTINCT FROM (NEW."last_reviewed_by_id") OR OLD."line" IS DISTINCT FROM (NEW."line") OR OLD."mitigated" IS DISTINCT FROM (NEW."mitigated") OR OLD."mitigated_by_id" IS DISTINCT FROM (NEW."mitigated_by_id") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."nb_occurences" IS DISTINCT FROM (NEW."nb_occurences") OR OLD."numerical_severity" IS DISTINCT FROM (NEW."numerical_severity") OR OLD."out_of_scope" IS DISTINCT FROM (NEW."out_of_scope") OR OLD."param" IS DISTINCT FROM (NEW."param") OR OLD."payload" IS DISTINCT FROM (NEW."payload") OR OLD."planned_remediation_date" IS DISTINCT FROM (NEW."planned_remediation_date") OR OLD."planned_remediation_version" IS DISTINCT FROM (NEW."planned_remediation_version") OR OLD."priority_bucket" IS DISTINCT FROM (NEW."priority_bucket") OR OLD."priority_calculated_at" IS DISTINCT FROM (NEW."priority_calculated_at") OR OLD."priority_score" IS DISTINCT FROM (NEW."priority_score") OR OLD."publish_date" IS DISTINCT FROM (NEW."publish_date") OR OLD."ransomware_used" IS DISTINCT FROM (NEW."ransomware_used") OR OLD."refs" IS DISTINCT FROM (NEW."refs") OR OLD."reporter_id" IS DISTINCT FROM (NEW."reporter_id") OR OLD."review_requested_by_id" IS DISTINCT FROM (NEW."review_requested_by_id") OR OLD."risk_accepted" IS DISTINCT FROM (NEW."risk_accepted") OR OLD."sast_sink_object" IS DISTINCT FROM (NEW."sast_sink_object") OR OLD."sast_source_file_path" IS DISTINCT FROM (NEW."sast_source_file_path") OR OLD."sast_source_line" IS DISTINCT FROM (NEW."sast_source_line") OR OLD."sast_source_object" IS DISTINCT FROM (NEW."sast_source_object") OR OLD."scanner_confidence" IS DISTINCT FROM (NEW."scanner_confidence") OR OLD."service" IS DISTINCT FROM (NEW."service") OR OLD."severity" IS DISTINCT FROM (NEW."severity") OR OLD."severity_justification" IS DISTINCT FROM (NEW."severity_justification") OR OLD."sla_expiration_date" IS DISTINCT FROM (NEW."sla_expiration_date") OR OLD."sla_start_date" IS DISTINCT FROM (NEW."sla_start_date") OR OLD."sonarqube_issue_id" IS DISTINCT FROM (NEW."sonarqube_issue_id") OR OLD."static_finding" IS DISTINCT FROM (NEW."static_finding") OR OLD."steps_to_reproduce" IS DISTINCT FROM (NEW."steps_to_reproduce") OR OLD."test_id" IS DISTINCT FROM (NEW."test_id") OR OLD."thread_id" IS DISTINCT FROM (NEW."thread_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."triage_assigned_to_id" IS DISTINCT FROM (NEW."triage_assigned_to_id") OR OLD."triage_due_date" IS DISTINCT FROM (NEW."triage_due_date") OR OLD."triage_reason" IS DISTINCT FROM (NEW."triage_reason") OR OLD."triage_state" IS DISTINCT FROM (NEW."triage_state") OR OLD."under_defect_review" IS DISTINCT FROM (NEW."under_defect_review") OR OLD."under_review" IS DISTINCT FROM (NEW."under_review") OR OLD."unique_id_from_tool" IS DISTINCT FROM (NEW."unique_id_from_tool") OR OLD."url" IS DISTINCT FROM (NEW."url") OR OLD."verified" IS DISTINCT FROM (NEW."verified") OR OLD."vuln_id_from_tool" IS DISTINCT FROM (NEW."vuln_id_from_tool"))', func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_confidence", "auto_triage_decision", "auto_triage_reason", "auto_triage_rule", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "priority_bucket", "priority_calculated_at", "priority_score", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "triage_assigned_to_id", "triage_due_date", "triage_reason", "triage_state", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."auto_triage_confidence", NEW."auto_triage_decision", NEW."auto_triage_reason", NEW."auto_triage_rule", NEW."auto_triaged_at", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."priority_bucket", NEW."priority_calculated_at", NEW."priority_score", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."triage_assigned_to_id", NEW."triage_due_date", NEW."triage_reason", NEW."triage_state", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='62411d965aefc6213f30383f7816ea3c90114cf8', operation='UPDATE', pgid='pgtrigger_update_update_92175', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "auto_triage_confidence", "auto_triage_decision", "auto_triage_reason", "auto_triage_rule", "auto_triaged_at", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "priority_bucket", "priority_calculated_at", "priority_score", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "triage_assigned_to_id", "triage_due_date", "triage_reason", "triage_state", "under_defect_review", "under_review", "unique_id_from_tool", "url", "verified", "vuln_id_from_tool") VALUES (OLD."active", OLD."auto_triage_confidence", OLD."auto_triage_decision", OLD."auto_triage_reason", OLD."auto_triage_rule", OLD."auto_triaged_at", OLD."component_name", OLD."component_version", OLD."created", OLD."cve", OLD."cvssv3", OLD."cvssv3_score", OLD."cvssv4", OLD."cvssv4_score", OLD."cwe", OLD."date", OLD."defect_review_requested_by_id", OLD."description", OLD."duplicate", OLD."duplicate_finding_id", OLD."dynamic_finding", OLD."effort_for_fixing", OLD."epss_percentile", OLD."epss_score", OLD."false_p", OLD."file_path", OLD."fix_available", OLD."hash_code", OLD."id", OLD."impact", OLD."is_mitigated", OLD."kev_date", OLD."known_exploited", OLD."last_reviewed", OLD."last_reviewed_by_id", OLD."last_status_update", OLD."line", OLD."mitigated", OLD."mitigated_by_id", OLD."mitigation", OLD."nb_occurences", OLD."numerical_severity", OLD."out_of_scope", OLD."param", OLD."payload", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."planned_remediation_date", OLD."planned_remediation_version", OLD."priority_bucket", OLD."priority_calculated_at", OLD."priority_score", OLD."publish_date", OLD."ransomware_used", OLD."refs", OLD."reporter_id", OLD."review_requested_by_id", OLD."risk_accepted", OLD."sast_sink_object", OLD."sast_source_file_path", OLD."sast_source_line", OLD."sast_source_object", OLD."scanner_confidence", OLD."service", OLD."severity", OLD."severity_justification", OLD."sla_expiration_date", OLD."sla_start_date", OLD."sonarqube_issue_id", OLD."static_finding", OLD."steps_to_reproduce", OLD."test_id", OLD."thread_id", OLD."title", OLD."triage_assigned_to_id", OLD."triage_due_date", OLD."triage_reason", OLD."triage_state", OLD."under_defect_review", OLD."under_review", OLD."unique_id_from_tool", OLD."url", OLD."verified", OLD."vuln_id_from_tool"); RETURN NULL;', hash='e54f86fd62908d5c9949c337f711d4c07b93152c', operation='DELETE', pgid='pgtrigger_delete_delete_72933', table='dojo_finding', when='AFTER')),
        ),
    ]
